### ISSUE TITLE
Could change feeds be used to view a sub-graph in a previous state?

### ISSUE THREAD

**Issue by venkatd** [graphaware/neo4j-changefeed#6]
I'm looking into being able to take a subset of the graph and view its state at a certain point in time. Is it theoretically possible to do this using the data the changefeed provides?

Thanks!

**Comment by bachmanm** [comment]
In theory - yes, but it would be very hard work. We have an auditing module in GraphAware Enterprise that allows for time-travel, but it is a commercial plugin. Please get in touch by email if you would like more info about it (info at graphaware dot com).
